sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=biarms/qemu-bin
    - VERSION=2.11.0

before_install:
  - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
  - >
    if [[ "${TRAVIS_BRANCH}" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      echo "We are building the master branch: version is official version."
      IMAGE_VERSION="${VERSION}"
      BETA_MODE="false"
    else
      echo "We are not building the master branch (or we are in a PR mode). Building a beta version then"
      IMAGE_VERSION="${VERSION}-beta-${BUILD_NUMBER}"
      BETA_MODE="true"
    fi
  - echo "IMAGE_VERSION=${IMAGE_VERSION} - TRAVIS_BRANCH=${TRAVIS_BRANCH} - DOCKER_USERNAME=${DOCKER_USERNAME}"
  # get qemu-arm-static binary
  - mkdir tmp
  - pushd tmp
  - curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v${VERSION}/x86_64_qemu-arm-static.tar.gz
  - tar xzf qemu-arm-static.tar.gz
  - curl -L -o qemu-aarch64-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v${VERSION}/x86_64_qemu-aarch64-static.tar.gz
  - tar xzf qemu-aarch64-static.tar.gz
  - popd

script:
  - VCS_REF=$(git rev-parse --short HEAD)
  - BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - docker build --build-arg VCS_REF=$VCS_REF --build-arg BUILD_DATE=${BUILD_DATE} --build-arg VERSION=${VERSION} -t ${IMAGE_NAME}:build .

after_success:
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker tag ${IMAGE_NAME}:build ${IMAGE_NAME}:${IMAGE_VERSION}
  - docker push ${IMAGE_NAME}:${IMAGE_VERSION}
  - >
    if [[ "${BETA_MODE}" == "false" ]]; then
      echo "Building master branch. Let's also push the 'latest' tag on docker hub"
      docker tag ${IMAGE_NAME}:build ${IMAGE_NAME}:latest
      docker push ${IMAGE_NAME}:latest
    fi
